# Generated by Django 3.2.9 on 2021-11-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('status', models.CharField(choices=[('+', 'in stock'), ('-', 'out of stock'), ('o', 'unknown')], default='o', max_length=12)),
            ],
        ),
    ]
