# Generated by Django 3.2.9 on 2021-11-09 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facolty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=72)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=72)),
                ('Facolty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facol.facolty')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=72)),
                ('Facolty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facol.facolty')),
                ('Lesson', models.ManyToManyField(to='facol.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=72)),
                ('Facolty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facol.facolty')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='Prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facol.prof'),
        ),
    ]
