# Generated by Django 3.2.9 on 2021-12-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20211204_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Drafted', 'Drafted'), ('Published', 'Published')], default='Drafted', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='update_on',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
