# Generated by Django 3.2.9 on 2021-12-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_auto_20211206_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_summery',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_tag',
            field=models.ManyToManyField(to='post.Tag'),
        ),
    ]
