# Generated by Django 3.2.9 on 2021-12-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_auto_20211206_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_tag',
            field=models.ManyToManyField(null=True, to='post.Tag'),
        ),
    ]
