# Generated by Django 3.2.9 on 2021-12-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20211202_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_tag',
            field=models.ManyToManyField(blank=True, null=True, to='post.Tag'),
        ),
    ]
