# Generated by Django 3.2.9 on 2021-11-26 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='creator',
        ),
    ]
