# Generated by Django 3.2.9 on 2021-12-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_category',
            field=models.ManyToManyField(blank=True, null=True, to='post.Category'),
        ),
    ]
