# Generated by Django 3.2.9 on 2021-11-07 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=72)),
                ('national_code', models.CharField(max_length=72)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=72)),
                ('discription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ListOfCom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=72)),
                ('price', models.PositiveIntegerField()),
                ('remaining', models.PositiveIntegerField()),
                ('discription', models.TextField()),
                ('puttosell_date', models.DateTimeField(auto_now_add=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.category')),
            ],
        ),
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=72)),
                ('national_code', models.CharField(max_length=72)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('cost', models.PositiveIntegerField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.buyers')),
                ('comodity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.listofcom')),
            ],
        ),
        migrations.CreateModel(
            name='ListOfInt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puttointrest_date', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.buyers')),
                ('comodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.listofcom')),
            ],
        ),
        migrations.AddField(
            model_name='listofcom',
            name='Seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.sellers'),
        ),
    ]
