# Generated by Django 3.2.9 on 2021-11-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PAY', 'payed'), ('NOT', 'notpayed')], default='NOT', max_length=9),
        ),
    ]
