# Generated by Django 3.2.9 on 2021-11-09 19:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_selleremail_sellers'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleremail',
            name='Sellers',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='order.sellers'),
            preserve_default=False,
        ),
    ]
