# Generated by Django 3.2.9 on 2021-11-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_selleremail_sellers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listofcom',
            name='Category',
        ),
        migrations.AddField(
            model_name='listofcom',
            name='Category',
            field=models.ManyToManyField(to='order.Category'),
        ),
    ]
