# Generated by Django 3.2.9 on 2021-11-16 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20211112_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listofcom',
            name='Category',
        ),
        migrations.AddField(
            model_name='listofcom',
            name='Category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.category'),
            preserve_default=False,
        ),
    ]
