# Generated by Django 3.2.9 on 2021-11-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20211116_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=72)),
            ],
        ),
        migrations.AddField(
            model_name='listofcom',
            name='Tag',
            field=models.ManyToManyField(to='order.Tag'),
        ),
    ]
