# Generated by Django 3.2.9 on 2021-11-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20211116_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofcom',
            name='status',
            field=models.CharField(choices=[('existing', 'existing'), ('notexisting', 'notexisting')], default='existing', max_length=20),
        ),
    ]
