# Generated by Django 3.2.9 on 2021-11-09 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyyerFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_number', models.PositiveIntegerField()),
                ('cost', models.PositiveIntegerField()),
                ('factor_pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellerFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_number', models.PositiveIntegerField()),
                ('cost', models.PositiveIntegerField()),
                ('factor_pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellerEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_text', models.TextField()),
                ('SellerFactor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.sellerfactor')),
                ('Sellers', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.sellers')),
            ],
        ),
        migrations.CreateModel(
            name='BuyyerEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_text', models.TextField()),
                ('Buyers', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.buyers')),
                ('BuyyerFactor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.buyyerfactor')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='BuyyerFactor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order.buyyerfactor'),
        ),
        migrations.AddField(
            model_name='order',
            name='SellerFactor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order.sellerfactor'),
        ),
    ]
