# Generated by Django 3.2.9 on 2021-11-09 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20211109_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selleremail',
            name='Sellers',
        ),
    ]
