# Generated by Django 3.2.9 on 2021-11-16 18:48

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_listofcom_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='listofcom',
            managers=[
                ('ex_and_no', django.db.models.manager.Manager()),
            ],
        ),
    ]
