version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    networks:
      - network
    
    env_file:
      - ./.env.dev
    depends_on:
      -postgressdb
  postgressdb:
      image: postgres:13.0-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        - POSTGRES_USER=hello_django
        - POSTGRES_PASSWORD=hello_django
        - POSTGRES_DB=hello_django_dev
      volumes:
        postgres_data:/var/lib/postgresql/data/

    
  redis_db:
    image: "redis:latest"
    command: redis-server --save 60 1 --loglevel warning
    networks:
      - network
networks:
  network:


